# Generated by Django 2.0.13 on 2019-04-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonaccinthnumber',
            name='fibonacci_nth_number',
            field=models.BigIntegerField(),
        ),
    ]
